### ISSUE TITLE
howto install in symfony

### ISSUE THREAD

**Issue by xub** [cobisja/tad-php#10]
hi, howto install this in symfony 

I must add in composer.json

  "require": {
??
Thank you

i copy direcoty TDAPHP in symfony/vendor 

Attempted to load class "TADFactory" from namespace "TADPHP".
Did you forget a "use" statement for another namespace?

**Comment by cobisja** [comment]
Hello my friend,

Sorry but at the time I wrote TAD-PHP I did not follow PSR standards so I
could not build a composer package.

I don't know Symfony (actually I did not like it at all!!! - Laravel,
Laravel, :-)) but I suppose it should be easy to integrate it in any
framework because TAD uses namespaces in a way that is very close to the
PSR standards. So, you have work to do my friend :-)

Best regards,

Cobis

2016-04-02 10:29 GMT-04:30 Sergio Sam notifications@github.com:
