### ISSUE TITLE
Imposible iniciar conexión con dispositivo

### ISSUE THREAD

**Issue by mahmoudgad94** [cobisja/tad-php#23]
Hi i try from Attendace Managment program all work fine but try tad-php not working 

Fatal error: Uncaught exception 'TADPHP\Exceptions\ConnectionError' with message 'Imposible iniciar conexión con dispositivo 192.168.1.201' in C:\xampp\htdocs\zk\tad\lib\TAD.php:408 Stack trace: #0 C:\xampp\htdocs\\zk\tad\lib\TAD.php(271): TADPHP\TAD->check_for_connection() #1 C:\xampp\htdocs\zk\index.php(26): TADPHP\TAD->__call('get_date', Array) #2 C:\xampp\htdocs\zk\index.php(26): TADPHP\TAD->get_date() #3 {main} thrown in C:\xampp\htdocs\zk\tad\lib\TAD.php on line 408

**Comment by cobisja** [comment]
Greetings!,

TAD-PHP only works on those devices with an integrated web server with SOAP
support (due I had a device like that). So, double check your device's
features in order to verify this requirement.

Beyond the mentioned above, right now it is almost impossible to provide an
affordable support for the library because I do not have any device for
development. I've got a few new ideas and also some others to fix some bugs
but unfortunately without a device I'm not able to implement any code.

Best regards,

Cobis

2017-03-19 7:23 GMT-04:00 mahmoudgad94 <notifications@github.com>:

**Comment by mahmoudgad94** [comment]
Oh thank you  , i thank my device not support SOAP

**Comment by wajishah** [comment]
Hi @cobisja
i got the same error with no trace of cause. The device is successfully connecting with its software and using `ZKlibrary` its returning the attendance records. But using your library its giving the above mentioned error But the SOAP is enables and working fine with ZKLibrary.

 
Any  help will be appreciated.
