### ISSUE TITLE
Improve speed of setting user

### ISSUE THREAD

**Issue by forexknight** [cobisja/tad-php#36]
Hi,

I would like to know if there is any option to push multiple users in one request, instead of executing function `set_user_info` for each user?

Each `set_user_info` execution takes about 0.5 second. For 100 users it would be 50 seconds. Could you suggest my how could I improve it?

**Comment by cobisja** [comment]
greetings,

As I said in the README.md file, there is not enough information about
ZK-SDK through SOAP. What I've implemented was based on the information I
found on internet.

About your question, I don't think you can improve the response time of
set_user_info method because the method only perform a SOAP call to the
device. Maybe,  you can take a different approach  through an external
resource. For instance, you can use a "job queue" for performing
asynchronous calls. This way,  you'll improve the response time, but I
don't know if this approach meet your needs.

Best regards,
