### ISSUE TITLE
UDP and SOAP

### ISSUE THREAD

**Issue by soylomass** [cobisja/tad-php#6]
I want to connect to a remote device. The router of the network where the device is, only has 4370 port opened. How can I make sure the Class won't try to connect using port 80?

Thanks

**Comment by cobisja** [comment]
You can be sure TAD-PHP tries to connect using port 80 because current version is designed to test if the device "is on-line" through a curl() call and it's supposed that the device has a webserver build-in (I had a device with webserver support in my last job).

So, if your device doesn't have a webserver built-in, TAD-PHP will refuse sending commands. I know this is a very annoying issue.

I have a new version but I don't have any device where to test it. In the meantime I won't commit changes until I can get a new device to run tests in a properly way.

Sorry,

Cobis
